{
    "webSeriesDataList": [
       {
         "id":"108",
         "ImageUrlHorizontal":"https://i.ibb.co/vJPbSFn/108H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/mGqmXT1/108V.jpg",
         "movieName":"Wrong Turn (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/3POv62vmAgha4v/HDKing.Vip_WR0N1GT3RNULS1P1720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/g8ji5vowv23d"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/3POv62vmAgha4v/HDKing.Vip_WR0N1GT3RNULS1P1720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/g8ji5vowv23d"},
         "keyName":"Wrong Turn 1",
         "pathName":"S1"
      },
      {
         "id":"109",
         "ImageUrlHorizontal":"https://i.ibb.co/dcSqRMv/109H.png",
         "ImageUrlVertical":"https://i.ibb.co/ZVGnz0P/109V.png",
         "movieName":"Life In a City (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"HottyNotty",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/vzeOeVVDrPt43Qo/HDKing.Vip_L1FIC3THN72H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/qo5ouz77vs69"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/vzeOeVVDrPt43Qo/HDKing.Vip_L1FIC3THN72H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/qo5ouz77vs69"},
         "keyName":"Life In a City 1",
         "pathName":"S1"
      },
      {
         "id":"110",
         "ImageUrlHorizontal":"https://i.ibb.co/60TDf2F/110H.webp",
         "ImageUrlVertical":"https://i.ibb.co/YWB20HY/110V.png",
         "movieName":"Charamsukh Jane Anjane Mein 5 (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/Xx02jMeQbpTD6vL/HDKing.Vip_C1HS3KUP1LS1E39720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/syb4hn3swzd8"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/Xx02jMeQbpTD6vL/HDKing.Vip_C1HS3KUP1LS1E39720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/syb4hn3swzd8"},
         "keyName":"Charamsukh Jane Anjane Mein 5",
         "pathName":"S1"
      }
        ]}
