{
    "webSeriesDataList": [
    
     {
         "id":"152",
         "ImageUrlHorizontal":"https://i.ibb.co/fntnt2n/152V.png",
         "ImageUrlVertical":"https://i.ibb.co/dPczGKV/152H.webp",
         "movieName":"CharmSukh: Tawa Garam (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/vgdbbpPyQXS4Xbm/HDKing.One_T1WG3RMS1P1720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/jo7naizh41od"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/vgdbbpPyQXS4Xbm/HDKing.One_T1WG3RMS1P1720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/jo7naizh41od"},
         "keyName":"CharmSukh: Tawa Garam 1",
         "pathName":"S1"
      },
      {
         "id":"146",
         "ImageUrlHorizontal":"https://i.ibb.co/hX8X209/146H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/xzRx8tx/146V.jpg",
         "movieName":"Titliyaan (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/xgdwVy9JVPukBVG/HDKing.BiZ_T1T3LY3NS1P1720PH3V.mkv","2":"https://streamtape.com/v/k2eXozBrYySOl8Q/HDKing.BiZ_T1T3LYS1P2720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/6moftavwe4ic","2":"https://streamhub.to/baipt010fpun"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/xgdwVy9JVPukBVG/HDKing.BiZ_T1T3LY3NS1P1720PH3V.mkv","2":"https://streamtape.com/v/k2eXozBrYySOl8Q/HDKing.BiZ_T1T3LYS1P2720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/6moftavwe4ic","2":"https://streamhub.to/baipt010fpun"},
         "keyName":"Titliyaan 1",
         "pathName":"S1"
      },
    {
         "id":"148",
         "ImageUrlHorizontal":"https://i.ibb.co/F8tghbg/148H.webp",
         "ImageUrlVertical":"https://i.ibb.co/ZJLGs0H/148V.jpg",
         "movieName":"Nalayak (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"PrimeShots",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/DAjzxVQQ8RUkOlY/HDKing.BiZ_N1L3YKPS1E172H.mkv","2":"https://streamtape.com/v/wagP8MGZjkSJrmB/HDKing.BiZ_N1L3YKPS1E272H.mkv",
         "3":"https://streamtape.com/v/dklL7D29YJT1jR/HDKing.BiZ_N1L3YKPS1E372H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/x7e3nj5vvahb","2":"https://streamhub.to/ccaleljttlql","3":"https://streamhub.to/nzxd9tdkxaes"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/DAjzxVQQ8RUkOlY/HDKing.BiZ_N1L3YKPS1E172H.mkv","2":"https://streamtape.com/v/wagP8MGZjkSJrmB/HDKing.BiZ_N1L3YKPS1E272H.mkv",
         "3":"https://streamtape.com/v/dklL7D29YJT1jR/HDKing.BiZ_N1L3YKPS1E372H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/x7e3nj5vvahb","2":"https://streamhub.to/ccaleljttlql","3":"https://streamhub.to/nzxd9tdkxaes"},
         "keyName":"Nalayak 1",
         "pathName":"S1"
      },
    {
         "id":"145",
         "ImageUrlHorizontal":"https://i.ibb.co/4MgrtdS/145H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/D9vNFg3/145V.jpg",
         "movieName":"CharmSukh: Tauba Tauba (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/OYmLdXw1VjtZj1p/HDKing.BiZ_T1UBT3BCHRMS1P1720PH3V.mkv","2":"https://streamtape.com/v/G66pW62My7i1vmG/HDKing.BiZ_T3BT3BCMKULS1P2720PH3VC.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/lch99fj04vky","2":"https://streamhub.to/cahzbr9zj4nt"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/OYmLdXw1VjtZj1p/HDKing.BiZ_T1UBT3BCHRMS1P1720PH3V.mkv","2":"https://streamtape.com/v/G66pW62My7i1vmG/HDKing.BiZ_T3BT3BCMKULS1P2720PH3VC.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/lch99fj04vky","2":"https://streamhub.to/cahzbr9zj4nt"},
         "keyName":"CharmSukh: Tauba Tauba 1",
         "pathName":"S1"
      },{
         "id":"129",
         "ImageUrlHorizontal":"https://i.ibb.co/XpQMg1q/129H.webp",
         "ImageUrlVertical":"https://i.ibb.co/j6c8yrB/129V.png",
         "movieName":"Chhupi Nazar (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Kooku",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/XgoMl18ZXkfDr26/HDKing.Fun_C1HPN3ZKOS1E172H.mkv","2":"https://streamtape.com/v/QKrkGpoYMQTgG6/HDKing.Fun_C1HPN3ZKOS1E272H.mkv",
         "3":"https://streamtape.com/v/DQrgKXwaQRIkMKk/HDKing.BiZ_C1H3PN3ZRS1E372H.mkv","4":"https://streamtape.com/v/pMxOV34z4DURXJ/HDKing.BiZ_C1H3NZS1E472H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/etr19un27sy8","2":"https://streamhub.to/r86deju7265u",
         "3":"https://streamhub.to/54llztls3bic","4":"https://streamhub.to/nm7vqcn9jc2h"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/XgoMl18ZXkfDr26/HDKing.Fun_C1HPN3ZKOS1E172H.mkv","2":"https://streamtape.com/v/QKrkGpoYMQTgG6/HDKing.Fun_C1HPN3ZKOS1E272H.mkv",
         "3":"https://streamtape.com/v/DQrgKXwaQRIkMKk/HDKing.BiZ_C1H3PN3ZRS1E372H.mkv","4":"https://streamtape.com/v/pMxOV34z4DURXJ/HDKing.BiZ_C1H3NZS1E472H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/etr19un27sy8","2":"https://streamhub.to/r86deju7265u",
         "3":"https://streamhub.to/54llztls3bic","4":"https://streamhub.to/nm7vqcn9jc2h"},
         "keyName":"Chhupi Nazar 1",
         "pathName":"S1"
      },
      {
         "id":"147",
         "ImageUrlHorizontal":"https://i.ibb.co/ZTT6PwL/147H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/thBsfV8/147V.jpg",
         "movieName":"Mera Baap Teri Mausi (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"DigimoviePlex",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/VW1LmPQq97CzJJ/HDKing.BiZ_M3RBPMS1E1T272H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/xb0qj2yeqcg6"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/VW1LmPQq97CzJJ/HDKing.BiZ_M3RBPMS1E1T272H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/xb0qj2yeqcg6"},
         "keyName":"Mera Baap Teri Mausi 1",
         "pathName":"S1"
      },
      {
         "id":"136",
         "ImageUrlHorizontal":"https://i.ibb.co/FVyS6wp/136H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/sWnmcJ0/136V.png",
         "movieName":"Sursuri Li (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/W1Zqqp2lj8fbw49/JMSP1_%282022%29_www.HDKing.Fun_720p_HEVC_HDRip_AAC_x264.mkv","2":"https://streamtape.com/v/9qR10BOpJetazQr/HDKing.BiZ_S3S3LULS1P2C3P720PH3V.mkv"
         ,"3":"https://streamtape.com/v/Za11YPpRA4TKA7/HDKing.BiZ_S3SUL1ULIS1P3720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/ebikwqv67ggf","2":"https://streamhub.to/f2hms1qp7zn1"
         ,"3":"https://streamhub.to/p2u5uux9wxhx"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/W1Zqqp2lj8fbw49/JMSP1_%282022%29_www.HDKing.Fun_720p_HEVC_HDRip_AAC_x264.mkv","2":"https://streamtape.com/v/9qR10BOpJetazQr/HDKing.BiZ_S3S3LULS1P2C3P720PH3V.mkv"
         ,"3":"https://streamtape.com/v/Za11YPpRA4TKA7/HDKing.BiZ_S3SUL1ULIS1P3720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/ebikwqv67ggf","2":"https://streamhub.to/f2hms1qp7zn1"
         ,"3":"https://streamhub.to/p2u5uux9wxhx"},
         "keyName":"Sursuri Li 1",
         "pathName":"S1"
      },
    {
         "id":"137",
         "ImageUrlHorizontal":"https://i.ibb.co/mFvQLVm/137H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/58w3xDC/137V.jpg",
         "movieName":"Choodiwala (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/2kpRa4K9VvIWbR/HDKing.BiZ_CH0DW3LS1P720pH3V.mkv","2":"https://streamtape.com/v/XoxmOX17azIDbqG/HDKing.BiZ_CH0DW3LULS1P2720pH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/1pn3p1ci4spr","2":"https://streamhub.to/bzjpcjqu59q8"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/2kpRa4K9VvIWbR/HDKing.BiZ_CH0DW3LS1P720pH3V.mkv","2":"https://streamtape.com/v/XoxmOX17azIDbqG/HDKing.BiZ_CH0DW3LULS1P2720pH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/1pn3p1ci4spr","2":"https://streamhub.to/bzjpcjqu59q8"},
         "keyName":"Choodiwala",
         "pathName":"S1"
      },
      {
         "id":"142",
         "ImageUrlHorizontal":"https://i.ibb.co/Nrd9tVQ/142H.webp",
         "ImageUrlVertical":"https://i.ibb.co/47cDnFj/142V.png",
         "movieName":"Shilajit (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"PrimeShots",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/2qA89pXwm4SZb0o/HDKing.BiZ_S1HL3JPSSE1E172H.mkv","2":"https://streamtape.com/v/kp02ZL8Vr6SOkRB/HDKing.BiZ_S1HL3JPSSE1E272H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/7pc39a1bnnqq","2":"https://streamhub.to/cnzw3zwl00yj"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/2qA89pXwm4SZb0o/HDKing.BiZ_S1HL3JPSSE1E172H.mkv","2":"https://streamtape.com/v/kp02ZL8Vr6SOkRB/HDKing.BiZ_S1HL3JPSSE1E272H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/7pc39a1bnnqq","2":"https://streamhub.to/cnzw3zwl00yj"},
         "keyName":"Shilajit 1",
         "pathName":"S1"
      },
      {
         "id":"139",
         "ImageUrlHorizontal":"https://i.ibb.co/zFthsv9/139H.webp",
         "ImageUrlVertical":"https://i.ibb.co/58Jd6Gh/139V.png",
         "movieName":"Mami No. 1 (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"CinePrime",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/e4q6JGzB74Ija6/HDKing.BiZ_M1MNS1P172H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/aw00ljq985zk"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/e4q6JGzB74Ija6/HDKing.BiZ_M1MNS1P172H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/aw00ljq985zk"},
         "keyName":"Mami No. 1 1",
         "pathName":"S1"
      }
        ]}
