{
    "webSeriesDataList": [
    {
         "id":"152",
         "ImageUrlHorizontal":"https://i.ibb.co/dPczGKV/152H.webp",
         "ImageUrlVertical":"https://i.ibb.co/fntnt2n/152V.png",
         "movieName":"CharmSukh: Tawa Garam (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/vgdbbpPyQXS4Xbm/HDKing.One_T1WG3RMS1P1720PH3V.mkv","2":"https://streamtape.com/v/p2bMoXxM4etrPOv/HDKing.One_CH1MS3KTWG3RMS1P2720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/jo7naizh41od","2":"https://streamhub.to/n4o1txaevy46"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/vgdbbpPyQXS4Xbm/HDKing.One_T1WG3RMS1P1720PH3V.mkv","2":"https://streamtape.com/v/p2bMoXxM4etrPOv/HDKing.One_CH1MS3KTWG3RMS1P2720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/jo7naizh41od","2":"https://streamhub.to/n4o1txaevy46"},
         "keyName":"CharmSukh: Tawa Garam 1",
         "pathName":"S1"
      },
      {
         "id":"149",
         "ImageUrlHorizontal":"https://i.ibb.co/hWMVM1L/149H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/f2mfq6c/149V.jpg",
         "movieName":"Jalebi Season 2 (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"RabbitMovies",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/vWRKAlxQPkU44Bz/HDKing.One_J1L3BS2E1T272H.mkv","2":"https://streamtape.com/v/gYZY04ywaDCYOV/HDKing.One_J1L3BRBTS1E3T572H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/u22b264t8xmn","2":"https://streamhub.to/f5ed8jy44d6f"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/vWRKAlxQPkU44Bz/HDKing.One_J1L3BS2E1T272H.mkv","2":"https://streamtape.com/v/gYZY04ywaDCYOV/HDKing.One_J1L3BRBTS1E3T572H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/u22b264t8xmn","2":"https://streamhub.to/f5ed8jy44d6f"},
         "keyName":"Jalebi 2",
         "pathName":"S1"
      },
      {
         "id":"147",
         "ImageUrlHorizontal":"https://i.ibb.co/ZTT6PwL/147H.jpg",
         "ImageUrlVertical":"https://i.ibb.co/thBsfV8/147V.jpg",
         "movieName":"Mera Baap Teri Mausi (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"DigimoviePlex",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/VW1LmPQq97CzJJ/HDKing.BiZ_M3RBPMS1E1T272H.mkv","2":"https://streamtape.com/v/AQjvgdBJqJiXJor/HDKing.One_M3RBPMSIS1E372H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/xb0qj2yeqcg6","2":"https://streamhub.to/od5c1u334jmu"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/VW1LmPQq97CzJJ/HDKing.BiZ_M3RBPMS1E1T272H.mkv","2":"https://streamtape.com/v/AQjvgdBJqJiXJor/HDKing.One_M3RBPMSIS1E372H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/xb0qj2yeqcg6","2":"https://streamhub.to/od5c1u334jmu"},
         "keyName":"Mera Baap Teri Mausi 1",
         "pathName":"S1"
      },
      {
         "id":"154",
         "ImageUrlHorizontal":"https://i.ibb.co/TRV6gRy/154H.webp",
         "ImageUrlVertical":"https://i.ibb.co/2v712DG/154V.jpg",
         "movieName":"Shaukeen Uncle (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"PrimeShots",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/06Bz4AvXMXsbya8/HDKing.One_SH1KNUCSPS1E172H.mkv","2":"https://streamtape.com/v/KQj9QjQ4dATwX2/HDKing.One_S1HKNU3CS1E272H.mkv",
         "3":"https://streamtape.com/v/vxG2AaKDdJIBA6/HDKing.One_SHK1NUCPSS1E372H.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/fnk23e8xqfv1","2":"https://streamhub.to/qbv85cgob216","3":"https://streamhub.to/tbu1cpvx38dh"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/06Bz4AvXMXsbya8/HDKing.One_SH1KNUCSPS1E172H.mkv","2":"https://streamtape.com/v/KQj9QjQ4dATwX2/HDKing.One_S1HKNU3CS1E272H.mkv",
         "3":"https://streamtape.com/v/vxG2AaKDdJIBA6/HDKing.One_SHK1NUCPSS1E372H.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/fnk23e8xqfv1","2":"https://streamhub.to/qbv85cgob216","3":"https://streamhub.to/tbu1cpvx38dh"},
         "keyName":"Shaukeen Uncle 1",
         "pathName":"S1"
      },
      {
         "id":"153",
         "ImageUrlHorizontal":"https://i.ibb.co/VVJyHjW/153H.webp",
         "ImageUrlVertical":"https://i.ibb.co/b1MYT7H/153V.png",
         "movieName":"Palang Tod: Siskiyaan (2022)",
         "directOne":"Adult,Fantasy",
         "imbd":"9.3",
         "rating":"HD 720p",
         "language":"Hindi",
         "catergory":"Ullu",
         "Industry":"webSeries",
         "latest":"FALSE",
         "latestCatergory":"FALSE",
         "EpisodeTape":{"1":"https://streamtape.com/v/e3QaaqWr3VUoVG/HDKing.One_P3T0DS1S3KY720PH3V.mkv"},
         "EpisodeHub":{"1":"https://streamhub.to/lbq3yhog73li"},
         "EpisodeTapeD":{"1":"https://streamtape.com/v/e3QaaqWr3VUoVG/HDKing.One_P3T0DS1S3KY720PH3V.mkv"},
         "EpisodeHubD":{"1":"https://streamhub.to/lbq3yhog73li"},
         "keyName":"Palang Tod: Siskiyaan 1",
         "pathName":"S1"
      }
        ]}
