[
   {
      "id":"1",
      "name":"Ullu",
      "image":"https://i.ibb.co/7ykmSc2/Ullu.jpg",
      "genre":"Ullu"
   },
   {
      "id":"2",
      "name":"Kooku",
      "image":"https://i.ibb.co/ccT5Vb0/kooku-logo.jpg",
      "genre":"Kooku"
   },
   {
      "id":"3",
      "name":"Hot MX",
      "image":"https://i.ibb.co/W5pt2mS/Hot-Mx-mod-apk-download.jpg",
      "genre":"HotMX"
   },
   {
      "id":"4",
      "name":"Rabbit Movies",
      "image":"https://i.ibb.co/2h47sHf/rabbbit-movies.png",
      "genre":"RabbitMovies"
   },
   {
      "id":"5",
      "name":"Filmy Murga",
      "image":"https://i.ibb.co/kx3CGJQ/filmymurga.jpg",
      "genre":"FilmyMurga"
   },
   {
      "id":"6",
      "name":"HotX Vip",
      "image":"https://i.ibb.co/HDGpNKZ/d1-WTpt-CF3pt-K6-PYba8-FXp2-R5-Zf-c-W-Er-Yw-QRZg-LNX4pig-P9-CJu-H8q0vsz-FBz-XGUMI.png",
      "genre":"Hotx"
   },
   {
      "id":"7",
      "name":"NeonX Vip",
      "image":"https://i.ibb.co/fDfRfcT/d-PLz89-Z75-POa-YGa9wdq-CHEP9e-Bj7wk-A2oxth-T0ad-Ul-UAI5w-I4-GTn-Pf-q-XWQqsn39ph-Sq.png",
      "genre":"Neonx"
   },
   {
      "id":"9",
      "name":"DigimoviePlex",
      "image":"https://i.ibb.co/bdvCybL/digimovieplex.jpg",
      "genre":"DigimoviePlex"
   },
   {
      "id":"10",
      "name":"Prime Flix",
      "image":"https://i.ibb.co/whpBH2x/prime-Flix.jpg",
      "genre":"PrimeFlix"
   },
   {
      "id":"11",
      "name":"BoomMovies",
      "image":"https://i.ibb.co/KbJqC04/boommovies.jpg",
      "genre":"BoomMovies"
   },
   {
      "id":"12",
      "name":"PrimeShots",
      "image":"https://i.ibb.co/RTpDX96/Prime-Shots.jpg",
      "genre":"PrimeShots"
   },
   {
      "id":"13",
      "name":"HotMasti",
      "image":"https://i.ibb.co/z2VrHXT/HotMasti.jpg",
      "genre":"HotMasti"
   },
   {
      "id":"14",
      "name":"CinePrime",
      "image":"https://i.ibb.co/dkPgN5n/cineprime.png",
      "genre":"CinePrime"
   },
   {
      "id":"15",
      "name":"HalKut",
      "image":"https://i.ibb.co/S79LBz1/halkut.jpg",
      "genre":"HalKut"
   },
   {
      "id":"16",
      "name":"HottyNaughty",
      "image":"https://i.ibb.co/RQZVnsH/hottnaughty.jpg",
      "genre":"HottyNaughty"
   },
   {
      "id":"17",
      "name":"WOW",
      "image":"https://i.ibb.co/zZrqX73/wow.jpg",
      "genre":"WOW"
   },
   {
   "id":"18",
   "name":"OTHER Movies",
   "image":"https://i.ytimg.com/vi/SB_XJBJjwzw/hqdefault.jpg",
   "genre":"other"
   },
   {
   "id":"19",
   "name":"MoodX Vip",
   "image":"https://i.ibb.co/zxPH9yb/Msq-Heva-Cp39-OR6-p2d1-NTb-Cp-Pt-VVNP2-k-Kit-Ryh-YU48-Qiaaw-FCo-AVQg-CMu-L6-Bytxhx-U.jpg",
   "genre":"Moodx"
   }
   
]
